# Generated by Django 5.1.4 on 2025-01-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_video_url_projectimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_ongoing',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
    ]
