# Generated by Django 5.1.4 on 2025-01-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_project_options_rename_start_date_project_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
