# Generated by Django 5.1.4 on 2025-01-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_workitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField(help_text='Enter the YouTube embed URL (e.g., https://www.youtube.com/embed/VIDEO_ID)')),
                ('order', models.IntegerField(default=0, help_text='Order in which the talk should appear')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
