# Generated by Django 5.1.4 on 2025-02-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_talk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Eduardo Castello', max_length=200, verbose_name='Site Title')),
                ('subtitle', models.CharField(default='Postdoctoral research fellow at MIT', max_length=200, verbose_name='Subtitle')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
