# Generated by Django 5.1.4 on 2025-02-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='introtext',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
