# Generated by Django 5.1.4 on 2025-02-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_introtext_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='introtext',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='introtext',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='introtext',
            name='scholar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
