# Generated by Django 5.1.4 on 2025-02-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_introtext_email_introtext_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
