# Generated by Django 5.1.4 on 2025-02-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_talk_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='introtext',
            name='cyphy_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
