# Generated by Django 5.1.4 on 2025-02-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_experiencedescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencedescription',
            options={'verbose_name_plural': 'Experience Description'},
        ),
        migrations.RemoveField(
            model_name='experiencedescription',
            name='order',
        ),
    ]
