# Generated by Django 5.1.4 on 2025-02-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_sitesettings_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('instructions', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Open Positions',
            },
        ),
    ]
