# Generated by Django 5.1.4 on 2025-02-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_openpositions'),
    ]

    operations = [
        migrations.AddField(
            model_name='openpositions',
            name='deadline',
            field=models.TextField(default='deadline'),
            preserve_default=False,
        ),
    ]
