# Generated by Django 5.1.4 on 2025-02-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_openpositions_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='live_link',
        ),
    ]
