# Generated by Django 5.1.4 on 2025-02-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_publication_archivelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='research_lines/')),
                ('video_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('projects', models.ManyToManyField(blank=True, related_name='research_lines', to='main.project')),
                ('publications', models.ManyToManyField(blank=True, related_name='research_lines', to='main.publication')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
