# Generated by Django 5.1.4 on 2025-02-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_researchline'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchline',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
