# Generated by Django 5.1.4 on 2025-03-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_researchline_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="talk",
            options={"ordering": ["-date"]},
        ),
        migrations.RemoveField(
            model_name="talk",
            name="order",
        ),
    ]
