# Generated by Django 5.1.4 on 2025-03-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_talk_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='language',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
