# Generated by Django 5.1.4 on 2025-03-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_talk_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="researchline",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
