# Generated by Django 5.1.4 on 2025-03-20 21:50

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    # Get the models
    Project = apps.get_model('main', 'Project')
    ResearchLine = apps.get_model('main', 'ResearchLine')
    
    # Update Project slugs
    for project in Project.objects.all():
        base_slug = slugify(project.title)
        slug = base_slug
        counter = 1
        
        # Keep trying until we find a unique slug
        while Project.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
            
        project.slug = slug
        project.save()
    
    # Update ResearchLine slugs
    for research in ResearchLine.objects.all():
        base_slug = slugify(research.title)
        slug = base_slug
        counter = 1
        
        # Keep trying until we find a unique slug
        while ResearchLine.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
            
        research.slug = slug
        research.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_project_slug_researchline_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
