# Generated by Django 5.1.4 on 2025-03-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_populate_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="researchline",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=200, unique=True),
        ),
    ]
