# Generated by Django 5.1.4 on 2025-03-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_alter_project_slug_alter_researchline_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="courses/")),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
