# Generated by Django 5.1.4 on 2025-03-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="keywords",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="main.keyword"
            ),
        ),
    ]
