# Generated by Django 5.1.4 on 2025-03-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_course_keywords"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-start_year"]},
        ),
        migrations.RemoveField(
            model_name="course",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="course",
            name="start_date",
        ),
        migrations.AddField(
            model_name="course",
            name="end_year",
            field=models.IntegerField(default=2013),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="period",
            field=models.CharField(
                default="Bachelor in Computer Science and Artificial Intelligence",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="program",
            field=models.CharField(
                default="Bachelor in Computer Science and Artificial Intelligence",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="start_year",
            field=models.IntegerField(default=2012),
            preserve_default=False,
        ),
    ]
