# Generated by Django 5.1.4 on 2025-03-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_alter_course_options_remove_course_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="syllabus",
            field=models.FileField(blank=True, upload_to="syllabi/"),
        ),
    ]
