# Generated by Django 5.1.4 on 2025-05-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_course_syllabus"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="calcom_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
