# Generated by Django 5.1.4 on 2025-05-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_sitesettings_calcom_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="introtext",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
