# Generated by Django 5.1.4 on 2025-05-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_introtext_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="calcom_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
